# Generated by Django 4.2.27 on 2026-01-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_branch_address_branch_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='google_map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
