# Generated by Django 4.2.27 on 2026-01-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address_line',
            field=models.TextField(blank=True, help_text='House no, street, landmark', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='area',
            field=models.CharField(blank=True, help_text='Area / locality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(default='India', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('DL', 'Delhi'), ('JK', 'Jammu & Kashmir'), ('LA', 'Ladakh'), ('AN', 'Andaman & Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra & Nagar Haveli and Daman & Diu'), ('PY', 'Puducherry')], db_index=True, max_length=2, null=True),
        ),
    ]
